name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./member/pom.xml
          mvn clean package -f ./author/pom.xml
          mvn clean package -f ./book/pom.xml
          mvn clean package -f ./bookworkflow/pom.xml

      - name: Docker Build and push for Member
        uses: docker/build-push-action@v4
        with:
          context: ./member
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/member:latest
            ghcr.io/${{ github.repository }}/member:${{ github.ref_name }}
            
      - name: Docker Build and push for Author
        uses: docker/build-push-action@v4
        with:
          context: ./author
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/author:latest
            ghcr.io/${{ github.repository }}/author:${{ github.ref_name }}
            
      - name: Docker Build and push for Book
        uses: docker/build-push-action@v4
        with:
          context: ./book
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/book:latest
            ghcr.io/${{ github.repository }}/book:${{ github.ref_name }}
            
      - name: Docker Build and push for Bookworkflow
        uses: docker/build-push-action@v4
        with:
          context: ./bookworkflow
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bookworkflow:latest
            ghcr.io/${{ github.repository }}/bookworkflow:${{ github.ref_name }}
            
